### ISSUE TITLE
Vundle missing

### ISSUE THREAD

**Issue by gduquesnay** [samnang/dotfiles#1]
Following the instruction in the readme this step doesn't work:
vim +BundleInstall +qall

I think you forgot to include vundle.  I've gotten it to work a few times by installing vundle manually but thought I would let you know.

**Comment by gduquesnay** [comment]
9 years to close it? ;)

**Comment by samnang** [comment]
> 9 years to close it? ;)

Haha, didn't notice there was an opened issue here.
